-- SMODS.Joker {
--     key = "shrimp",
--     name = "Shrimp",
--     config = {
--         extra = {
            
--         }
--     },
--     pos = { x = 8, y = 0 },
--     cost = 1,
--     rarity = 1,
--     blueprint_compat = true,
--     atlas = "joker",
--     loc_vars = function(self, info_queue, card)
--         return {
--             vars = {
                
--             }
--         }
--     end,
--     calculate = function(self, card, context)
--     end
-- }